server: 
  port: 8020
spring: 
  application: 
    name: mymicroservice-consumer-movie-feign-hystrix-fallback-stream
eureka: 
  client: 
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/
  instance: 
    # 将自己的IP注册到Eureka Server。
    # 默认为false，表示注册微服务所在操作系统的hostname到Eureka Server。
    prefer-ip-address: true
