eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
spring:
  application:
    name: blog-service
  cloud:
    config:
      fail-fast: true
  profiles:
    active: pro