eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 5006
spring:
  application:
    name: monitoring-service
turbine:
  aggregator:
    cluster-config: default
  app-config: user-service,uaa-service
  cluster-name-expression: new String("default")
management:
  security:
    enabled: false
security:
  basic:
    enabled: false