server: 
  port: 8010
spring: 
  zipkin: 
    base-url: http://localhost:9411
  sleuth: 
    sampler: 
      percentage: 1.0
  application:
    name: mymicroservice-consumer-movie
logging:                       
  level: 
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG