spring:
  application:
    name: message-server
server:
  port: 8002
  servlet:
    context-path: /message-info/
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:9999/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    prefer-ip-address: true

