server:
  port: 8766


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


spring:
  application:
    name: gateway-api



zuul:
  routes:
    api-c:
      path: /api-c/**
      serviceId: service-consumer
    api-f:
      path: /api-f/**
      serviceId: service-feign