#management:
#  security:
#    enabled: false
#spring:
#  boot:
#    admin:
#      turbine:
#        clusters: default
#        location: monitor-service
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    metadata-map:
      user.name: admin
      user.password: 123456
spring:
  application:
    name: admin-service
server:
  port: 5001
security:
  user:
    name: admin
    password: 123456