apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 32080
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  template:
    metadata:
      name: keycloak
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: jboss/keycloak:5.0.0
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /tmp/
              name: keycloak-init
          env:
            - name: DB_VENDOR
              value: h2
            - name: KEYCLOAK_USER
              value: admin
            - name: KEYCLOAK_PASSWORD
              value: admin
            - name: KEYCLOAK_IMPORT
              value: /tmp/realm-export.json
      restartPolicy: Always
      volumes:
        - name: keycloak-init
          hostPath:
            # 该路径看自己机器的路径进行修改。
            path: /Users/reno/develop/code_mine/spring-cloud-yes/kubernetes/config/keycloak
  selector:
    matchLabels:
      app: keycloak

# ref：https://hub.docker.com/r/jboss/keycloak