apiVersion: v1
kind: Service
metadata:
  name: turbine-server
spec:
  selector:
    app: turbine-server
  ports:
    - port: 8989
      targetPort: 8989
      nodePort: 32089
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: turbine-server
  labels:
    app: turbine-server
spec:
  replicas: 1
  template:
    metadata:
      name: turbine-server
      labels:
        app: turbine-server
    spec:
      containers:
        - name: turbine-server
          image: reg.itmuch.com/itmuch/turbine-stream-server
          imagePullPolicy: IfNotPresent
          env:
            - name: PROFILE
              value: "k8s"
            - name: CONSUL_HOST
              value: "consul"
            - name: CONSUL_PORT
              value: "8500"
      restartPolicy: Always
  selector:
    matchLabels:
      app: turbine-server
