apiVersion: v1
kind: Service
metadata:
  name: zuul-server
spec:
  selector:
    app: zuul-server
  ports:
    - port: 5566
      targetPort: 5566
      nodePort: 32006
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zuul-server
  labels:
    app: zuul-server
spec:
  replicas: 1
  template:
    metadata:
      name: zuul-server
      labels:
        app: zuul-server
    spec:
      containers:
        - name: zuul-server
          image: reg.itmuch.com/itmuch/zuul-server
          imagePullPolicy: IfNotPresent
          env:
            - name: PROFILE
              value: "k8s"
            - name: CONSUL_HOST
              value: "consul"
            - name: CONSUL_PORT
              value: "8500"
      restartPolicy: Always
  selector:
    matchLabels:
      app: zuul-server
