eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 8771
spring:
  application:
    name: zipkin-client
  zipkin:
    base-url: http://localhost:8770
  sleuth:
    sampler:
      percentage: 1.0