spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/nigulasizhaosier/spring-cloud-config
          username: 13840935238@163.com
          password: znb8388953+
          search-paths: config
      label: master

foo1: 123123
