server:
  port: 8002

swagger:
  title: 短信平台缓存服务API列表
  description: 没有描述
  contactName: zouning
  email: 156090017@qq.com
  licenseUrl: https://www.apache.org/licenses/LICENSE-2.0
  version: 9020.2020.2020
  basePackge: com.itqf.smsplatform.cache.controller