spring:
  datasource:
    url: jdbc:mysql://192.168.1.33:3306/demo?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=round
    username: sa
    password: 12345678
  redis:
    database: 0
    host: 192.168.1.33
    password: null
    port: 6379
    timeout: 300000
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1
      min-idle: 0