server: 
  port: 8010
spring: 
  rabbitmq: 
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  sleuth: 
    sampler: 
      percentage: 1.0
  application:
    name: mymicroservice-consumer-movie
logging:                       
  level: 
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG