microservice-discovery-eureka:
  image: reg.itmuch.com/microservice-discovery-eureka
  ports:
  - 8761:8761
  hostname: discovery
microservice-provider-user:
  image: reg.itmuch.com/microservice-provider-user
  ports:
  - 8000:8000
  links:
  - microservice-discovery-eureka
microservice-consumer-movie-ribbon-with-hystrix:
  image: reg.itmuch.com/microservice-consumer-movie-ribbon-with-hystrix
  ports:
  - 8011:8011
  links:
  - microservice-discovery-eureka
  hostname: ribbon
microservice-hystrix-dashboard:
  image: reg.itmuch.com/microservice-hystrix-dashboard
  ports:
  - 8030:8030
  links:
  - microservice-discovery-eureka
  - microservice-hystrix-turbine
microservice-hystrix-turbine:
  image: reg.itmuch.com/microservice-hystrix-turbine
  ports:
  - 8031:8031
  links:
  - microservice-discovery-eureka
  - microservice-consumer-movie-ribbon-with-hystrix
microservice-api-gateway:
  image: reg.itmuch.com/microservice-api-gateway
  ports:
  - 8050:8050
  links:
  - microservice-discovery-eureka
  - microservice-consumer-movie-ribbon-with-hystrix
