zuul:
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  routes:
    user-service:
      path: /userapi/**
      service-id: user-service
      sensitive-headers:
    blog-service:
      path: /blogapi/**
      service-id: blog-service
      sensitive-headers:
    zipkin-client:
          path: /zipkinclient/**
          service-id: zipkin-client
          sensitive-headers:
server:
  port: 5000
spring:
  application:
    name: gateway-service
  zipkin:
    base-url: http://localhost:8770
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/