server:
  port: 9090
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-cloud-auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
    username: mysql_test
    password: mysql_test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://localhost:8770
  sleuth:
    sampler:
      percentage: 1.0
feign:
  hystrix:
    enabled: true

jwt:
  authorization: Basic dXNlci1zZXJ2aWNlOjEyMzQ1Ng==
  grant-type: password
management:
  security:
    enabled: false
logging:
  level: trace
