server: 
  port: 8010
spring: 
  application:
    name: mymicroservice-consumer-movie
logging:                       
  level: 
    root: INFO
    org.springframework.web.servlet.DispatcherServlet: DEBUG