spring:
  application:
    name: uaa-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: mysql_test
    password: mysql_test
    url: jdbc:mysql://localhost:3306/spring-cloud-auth?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  zipkin:
    base-url: http://localhost:8770
  sleuth:
    sampler:
      percentage: 1.0
server:
  port: 9999
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
client-id: user-service
client-secret: 123456
logging:
  level: trace

